---
- name: copy scripts
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: '/home/vagrant/{{ item }}'
    owner: vagrant
    group: vagrant
    mode: '0755'
  loop:
    - failcount.sh
    - failkill.sh
