---
- name: Copy a new network configuration "interfaces" file into place, after passing validation with ifup
  ansible.builtin.copy:
    src: eth1_cfg
    dest: /etc/network/interfaces.d/eth1_cfg
    validate: /usr/sbin/ifup --no-act -i %s eth1
  notify: Restart Networking

- name: Install Dnsmasq
  ansible.builtin.apt:
    name: dnsmasq
    update_cache: true

- name: Copy Dnsmasq configuration
  ansible.builtin.copy:
    src: dnsmasq.conf
    dest: '/etc/dnsmasq.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: Restart Dnsmasq

- name: Enable Dnsmasq at boot
  ansible.builtin.systemd:
    name: dnsmasq.service
    state: started
    enabled: yes

- name: Copy syslog configuration
  ansible.builtin.copy:
    src: createdumps.conf
    dest: '/etc/rsyslog.d/'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: Restart rsyslog

- name: Enable Contrib Non-Free
  ansible.builtin.replace:
    path: /etc/apt/sources.list
    regexp: 'main$'
    replace: 'main contrib non-free'

- name: Install SNMP and Mibs
  ansible.builtin.apt:
    name: [ snmp, snmp-mibs-downloader ]
    update_cache: true

- name: Enable MIBS
  ansible.builtin.replace:
    path: /etc/snmp/snmp.conf
    regexp: '^mibs :'
    replace: '# mibs :'

- name: Copy managedump.sh script in Controller
  ansible.builtin.copy:
    src: managedump.sh
    dest: '/usr/bin/'
    owner: 'root'
    group: 'root'
    mode: '0740'

- name: Run managedump.sh every 3 min
  ansible.builtin.cron:
    name: "managedump"
    minute: "3"
    job: "/usr/bin/managedump.sh"
