---
- name: Install Dnsmasq
  ansible.builtin.apt:
    name: dnsmasq
    update_cache: true

- name: Copy Dnsmasq configuration
  ansible.builtin.copy:
    src: dnsmasq.conf
    dest: '/etc/dnsmasq.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: Restart Dnsmasq

- name: Enable Dnsmasq at boot
  ansible.builtin.systemd:
    name: dnsmasq.service
    state: started
    enabled: yes


