# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "debian/bookworm64"
  config.vm.provider "virtualbox" do |vb|
    vb.linked_clone = true
  end

  (1..1).each do |i|
    config.vm.define "Client#{i}" do |machine|
      machine.vm.hostname = "Client#{i}"
	    machine.vm.network "private_network", virtualbox__intnet: "LAN1", auto_config: false
      machine.vm.synced_folder ".", "/vagrant", disabled: true
      machine.vm.provision "ansible" do |ansible|
        ansible.playbook = "site.yml"
      end
    end
  end

  config.vm.define "Router" do |machine|
    machine.vm.hostname = "Router"
    machine.vm.network "private_network", virtualbox__intnet: "LAN1", auto_config: false
    machine.vm.network "private_network", virtualbox__intnet: "LAN2", auto_config: false
    machine.vm.synced_folder ".", "/vagrant", disabled: true
    machine.vm.provision "ansible" do |ansible|
      ansible.playbook = "site.yml"
    end
  end

  (1..2).each do |i|
    config.vm.define "Server#{i}" do |machine|
      machine.vm.hostname = "Server#{i}"
      machine.vm.network "private_network", virtualbox__intnet: "LAN2", auto_config: false
      machine.vm.network "private_network", virtualbox__intnet: "TMP", auto_config: false
      machine.vm.synced_folder ".", "/vagrant", disabled: true
      machine.vm.provision "ansible" do |ansible|
        ansible.playbook = "site.yml"
      end
    end
  end
end
