---
- name: Restart Networking
  ansible.builtin.service:
    name: networking
    state: restarted

- name: Restart snmpd
  ansible.builtin.service:
    name: snmpd.service
    state: restarted

- name: Restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted
