---
- hosts: client-*
  become: true
  roles:
   #- set_proxy
   - common
   - eth1dhcp
   - snmpd

- hosts: r1
  become: true
  roles:
   #- set_proxy
   - common
   - netr1
   - ipforward
   - dnsmasqr1
   - snmpclient

