# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "debian/bookworm64"
  config.vm.provider "virtualbox" do |vb|
    vb.linked_clone = true
  end

  config.vm.define "client" do |machine|
    machine.vm.hostname = "client"
    machine.vm.network "private_network", virtualbox__intnet: "LAN", ip: "10.1.1.1"
    machine.vm.provision "ansible" do |ansible|
      ansible.playbook = "site.yml"
    end
  end

  config.vm.define "server" do |machine|
    machine.vm.hostname = "server"
    machine.vm.network "private_network", virtualbox__intnet: "LAN", ip: "10.1.1.2"
    machine.vm.provision "ansible" do |ansible|
      ansible.playbook = "site.yml"
    end
  end
end
