---
- name: Install tcpdump
  ansible.builtin.apt:
    name: tcpdump
    update_cache: true

- name: Copy syslog configuration
  ansible.builtin.copy:
    src: syslog_tcpdump.conf
    dest: '/etc/rsyslog.d/'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: Restart rsyslog

- name: Copy scripts in Controller
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: '/usr/bin/'
    owner: 'root'
    group: 'root'
    mode: '0740'
  loop:
    - netmon.sh
    - connection-monitor.sh

