---
- hosts: client-*
  become: true
  roles:
   - set_proxy
   - common
   - eth1dhcp

- hosts: r1
  become: true
  roles:
   - set_proxy
   - common
   - netr1
   - ipforward
   - dnsmasqr1

- hosts: r2
  become: true
  roles:
   - set_proxy
   - common
   - ipforward
   - netr2

- hosts: server
  become: true
  roles:
   - set_proxy
   - common
   - netserver
