---
- hosts: all
  become: true
  roles:
   - role: common

- hosts: agent1
  become: true
  roles:
   - role: agent

- hosts: agent2
  become: true
  roles:
   - role: agent

- hosts: controller
  become: true
  roles:
   - role: controller
