---
- name: Add static entry for client to /etc/hosts
  ansible.builtin.lineinfile:
    path: '/etc/hosts'
    line: '10.1.1.1 client'

- name: Add static entry for server to /etc/hosts
  ansible.builtin.lineinfile:
    path: '/etc/hosts'
    line: '10.2.2.2 server'
