---
- name: Restart Networking
  ansible.builtin.service:
    name: networking
    state: restarted

- name: Restart Dnsmasq
  ansible.builtin.service:
    name: dnsmasq
    state: restarted

- name: Restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted
