---
- name: Copy a new eth1 configuration "interfaces" file into place, after passing validation with ifup
  ansible.builtin.copy:
    src: r1eth1
    dest: /etc/network/interfaces.d/eth1
    validate: /usr/sbin/ifup --no-act -i %s eth1
  notify: Restart Networking
