---
- name: Copy rsyslog configuration enable remote log
  ansible.builtin.copy:
    src: rsyslog.conf
    dest: '/etc/rsyslog.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: Restart rsyslog
