Vagrant.configure("2") do |config| 
   config.vm.box = "debian/bookworm64"

   config.vm.provider "virtualbox" do |vb|
      vb.linked_clone = true
   end     
   config.vm.define "client1" do |machine|
      machine.vm.hostname = "client1"
      machine.vm.network "private_network", virtualbox__intnet: "LAN1", auto_config: false
      machine.vm.provision "ansible" do |ansible|
        ansible.playbook = "client1.yml"
      end
   end

   config.vm.define "r1" do |machine|
      machine.vm.hostname = "r1"
      machine.vm.network "private_network", virtualbox__intnet: "LAN1", auto_config: false
      machine.vm.network "private_network", virtualbox__intnet: "LAN2", auto_config: false
      machine.vm.provision "ansible" do |ansible|
        ansible.playbook = "r1.yml"
      end
   end

   config.vm.define "client2" do |machine|
      machine.vm.hostname = "client2"
      machine.vm.network "private_network", virtualbox__intnet: "LAN2", auto_config: false
      machine.vm.provision "ansible" do |ansible|
        ansible.playbook = "client2.yml"
      end 
   end

end
