---  
- name: Router enable forwarding
    ansible.builtin.replace:
      path: /etc/sysctl.conf
      regexp: '^#net\.ipv4\.ip_forward=1$'
      replace: 'net.ipv4.ip_forward=1'
    notify: Reload Sysctl
