---
- name: Copy scripts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /bin/
    owner: root
    group: root
    mode: "700"
  loop:
    - create-home.sh

- name: schedule with cron
  ansible.builtin.cron:
    name : create-home.sh
    minute: "*/2"
    hour: "6-22"
    weekday: "1-6"
    user: vagrant
    job: "/usr/bin/create-home.sh >/dev/null"