---
- name: Install snmpd
  ansible.builtin.apt:
    name: snmpd
    state: present

- name: Configure snmpd
  ansible.builtin.copy:
    src: snmpd.conf
    dest: /etc/snmp/snmpd.conf
  notify: Restart snmpd
